project:
  type: website
  output-dir: _site
  resources:
    - "chapters/"
    - "guidebook/"
    - "handouts/"
    - "images/"
    - "raw_documents/"

website:
  title: "The Rittenhouse Residence"
  description: "Historic luxury lodging at 1822 Pine Street, Philadelphia. Family-operated in a meticulously preserved 1854 townhouse near Rittenhouse Square."
  site-url: https://therittenhouseresidence.com
  repo-url: https://github.com/1822-pine/website
  
  navbar:
    background: primary
    logo: images/logo.png
    title: "The Rittenhouse Residence"
    left:
      - text: "The Residence"
        menu:
          - text: "Photo Gallery"
            href: gallery.qmd
            icon: images
          - text: "Floor Plans & Amenities"
            href: floor-plans-events.qmd
            icon: map
          - text: "The Neighborhood"
            href: neighborhood-guide.qmd
            icon: geo-alt

      - href: story.qmd
        text: "The Story"

      - href: events.qmd
        text: "Events & Retreats"

      - text: "Plan Your Stay"
        menu:
          - text: "Guest Guidebook"
            href: guidebook/guest-guidebook-2024.qmd
            icon: book
          - text: "FAQ"
            href: faq.qmd
            icon: question-circle
          - text: "House Rules & Policies"
            href: house-rules.qmd
            icon: info-circle

    right:
      - href: rates.qmd
        text: "Book Now"
        icon: calendar-check
      - href: contact.qmd
        text: "Contact"
        icon: envelope-fill
  
  page-footer:
    background: light
    left: |
      © 2024 The Rittenhouse Residence<br>
      Meticulously preserved since 1854
    center: |
      1822 Pine Street<br>
      Philadelphia, PA 19103<br>
      [info@therittenhouseresidence.com](mailto:info@therittenhouseresidence.com)
    right: |
      [Terms](terms.qmd) | [Privacy](privacy.qmd)<br>
      [Instagram](https://instagram.com/therittenhouseresidence) | [Facebook](https://facebook.com/therittenhouseresidence)

  search:
    location: navbar
    type: overlay
  
  google-analytics: "G-XXXXXXXXXX"
  
  comments:
    hypothesis: false

format:
  html:
    theme:
      light: [cosmo, styles/custom.scss]
      dark: [slate, styles/custom-dark.scss]
    css: styles/main.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: "On This Page"
    number-sections: false
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    anchor-sections: true
    
    include-in-header:
      - text: |
          <!-- SEO Meta Tags -->
          <meta name="author" content="The Rittenhouse Residence">
          <meta name="keywords" content="Philadelphia luxury lodging, Rittenhouse Square hotel, historic townhouse rental, 1822 Pine Street, corporate retreats, family reunions">
          <meta property="og:title" content="The Rittenhouse Residence - Historic Luxury Lodging & Event Space">
          <meta property="og:description" content="Experience Philadelphia's history in a meticulously preserved 1854 townhouse. Ideal for luxury stays, family reunions, and corporate retreats.">
          <meta property="og:image" content="https://therittenhouseresidence.com/images/property/DSC00084.jpg">
          <meta property="og:url" content="https://therittenhouseresidence.com">
          <meta property="og:type" content="website">
          <meta name="twitter:card" content="summary_large_image">
          
          <!-- Structured Data for Lodging Business -->
          <script type="application/ld+json">
          {
            "@context": "https://schema.org",
            "@type": "LodgingBusiness",
            "name": "The Rittenhouse Residence",
            "description": "Historic luxury lodging and event space in a preserved 1854 townhouse",
            "url": "https://therittenhouseresidence.com",
            "telephone": "+1-215-XXX-XXXX",
            "email": "info@therittenhouseresidence.com",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "1822 Pine Street",
              "addressLocality": "Philadelphia",
              "addressRegion": "PA",
              "postalCode": "19103",
              "addressCountry": "US"
            },
            "geo": {
              "@type": "GeoCoordinates",
              "latitude": 39.9477,
              "longitude": -75.1732
            },
            "image": [
              "https://therittenhouseresidence.com/images/property/DSC00084.jpg",
              "https://therittenhouseresidence.com/images/property/DSC00066.jpg"
            ],
            "priceRange": "$1600-$2500",
            "amenityFeature": [
              {"@type": "LocationFeatureSpecification", "name": "Historic Property"},
              {"@type": "LocationFeatureSpecification", "name": "Full Kitchen"},
              {"@type": "LocationFeatureSpecification", "name": "WiFi"},
              {"@type": "LocationFeatureSpecification", "name": "Air Conditioning"},
              {"@type": "LocationFeatureSpecification", "name": "Event Space"}
            ],
            "checkinTime": "16:00",
            "checkoutTime": "11:00",
            "numberOfRooms": 5,
            "petsAllowed": false,
            "smokingAllowed": false
          }
          </script>
          
          <!-- Favicon -->
          <link rel="icon" type="image/png" href="/favicon.png">
          <link rel="apple-touch-icon" href="/apple-touch-icon.png">

bibliography: ../refs/bibliography_complete.bib
csl: styles/chicago-fullnote-bibliography.csl

execute:
  echo: false
  warning: false