name: Deploy Quarto Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'
      
      - name: Install R (if needed for any computations)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
        if: false  # Set to true if you need R
      
      - name: Install Python (for any Python code blocks)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          pip install jupyter
          pip install pandas pyyaml
        if: hashFiles('requirements.txt') != ''
      
      - name: Render Quarto Website
        run: |
          cd website
          quarto render
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: website/_site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
        
      - name: Comment on PR with preview link
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment ready!'
            })